name: Gitleaks scan

on:
  push:
    branches:
    - workflow_testing

jobs:
  gitleaks-codescan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Print GITHUB_RUN_ID
        run: echo "Ref name is $GITHUB_RUN_ID"

      - name: Create empty JSON file in workspace
        run: |
          FILE_PATH="$GITHUB_WORKSPACE/store/request/request.json"
          mkdir -p "$(dirname "$FILE_PATH")"
          touch "$FILE_PATH"
          echo "File created at: $FILE_PATH"

      - name: Gitleaks scan
        uses: cloudbees-io/gitleaks-github-test@v2
        with:
          cloudbees_pat_token: ${{ secrets.CLOUDBEES_HD_PAT }}
          is-github-workflow: true
          cloudbees_api_url: ${{ vars.CB_PREPROD_API_URL }}
          run_id: "14377182881"
          job_id: $JOB_ID
          step_id: $STEP_ID 
