name: Trivy Hybrid Scan

on:
  push:
    branches:
      - workflow_testing

jobs:
  trivy-hybrid-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Print GITHUB_RUN_ID
        run: echo "Ref name is $GITHUB_RUN_ID"

      - name: Create empty JSON file in workspace
        run: |
          FILE_PATH="$GITHUB_WORKSPACE/store/request/request.json"
          mkdir -p "$(dirname "$FILE_PATH")"
          touch "$FILE_PATH"
          echo "File created at: $FILE_PATH"

      - name: Create tar of source code
        run: |
          tar -cvf output.tar .
          tar -tf output.tar

      - name: Run Trivy scan
        uses: cloudbees-io/trivy-github-test@v1
        with:
          binary-tar-path: output.tar
          cloudbees_pat_token: ${{ secrets.CLOUDBEES_HD_PAT }}
          is-github-workflow: true
          cloudbees_api_url: ${{ vars.CB_PREPROD_API_URL }}
          run_id: "14377182881"
          job_id: $JOB_ID
          step_id: $STEP_ID 
